service: afex-project
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  region: sa-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamoDb:*
      Resource:
        - arn:aws:dynamodb:sa-east-1:829812503451:table/Videos
        

functions:
  getVideos:
    handler: src/getVideos.getVideos
    events:
      - httpApi:
          path: /
          method: get
  addVideo:
    handler: src/addVideo.addVideo
    events:
      - httpApi:
          path: /add
          method: post
  deleteVideo:
    handler: src/deleteVideo.deleteVideo
    events:
      - httpApi:
          path: /delete/{id}
          method: delete

resources:
  Resources:
    Videos:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Videos
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
